image: node:22.14.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .pnpm-store

before_script:
  - corepack enable
  - pnpm install

stages:
  - lint
  - test
  - build
  - release

lint:
  stage: lint
  script:
    - pnpm run lint

unit_tests:
  stage: test
  script:
    - pnpm test

build:
  stage: build
  script:
    - pnpm run build
  artifacts:
    paths:
      - dist

release:
  stage: release
  script:
    - npx semantic-release
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: on_success
    - when: never
